name: 'Shellcheck Problem Matchers'
description: 'Automatically show shellcheck output as annotations in GitHub'
branding:
  icon: list
  color: purple
inputs:
  format:
    description: 'A specific shellcheck output format to match'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
