name: "Test shellcheck problem matchers"
on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v2-beta
    - run : npm ci
    - run: npm run lint

  test-all-formats:
    name: Run Action without specifying a format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
    # Run shellcheck and expect it to fail wit exit code 1
    - run: shellcheck test/fixtures/*.sh; [[ $? == 1 ]]; exit $?
      shell: bash {0}

  test-specific-format:
    name: Run Action with a specific format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        format: gcc
    # Run shellcheck and expect it to fail wit exit code 1
    - run: shellcheck -f gcc test/fixtures/*.sh; [[ $? == 1 ]]; exit $?
      shell: bash {0}
